import time
import schedule
import random
from faker import Faker
from sqlalchemy import create_engine, text
import oracledb
import pandas as pd
import os
import warnings

warnings.filterwarnings('ignore')

fake = Faker('es_ES')
PASS_SIMPLE = os.getenv('DB_PASS_SIMPLE', 'Udla2026_SeeleStore')
PASS_COMPLEX = os.getenv('DB_PASS_COMPLEX', 'Udla_2026_Secure!')

def get_mariadb():
    return create_engine(f'mysql+pymysql://root:{PASS_SIMPLE}@mariadb:3306/ComercioDB')

def get_sqlserver_master():
    return create_engine(f'mssql+pyodbc://sa:{PASS_COMPLEX}@mssql:1433/master?driver=ODBC+Driver+17+for+SQL+Server&TrustServerCertificate=yes')

def get_sqlserver_analytics():
    return create_engine(f'mssql+pyodbc://sa:{PASS_COMPLEX}@mssql:1433/AnalyticsDB?driver=ODBC+Driver+17+for+SQL+Server&TrustServerCertificate=yes')

def get_oracle_conn():
    params = oracledb.ConnectParams(host="oracle", port=1521, service_name="XE")
    return oracledb.connect(user="system", password=PASS_SIMPLE, params=params)

def setup_db():
    print(">>> 1. Verificando/Creando Tablas...")
    maria_ready = False
    while not maria_ready:
        try:
            eng = get_mariadb()
            with eng.connect() as conn:
                conn.execute(text("CREATE TABLE IF NOT EXISTS clientes (id INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(100), ciudad VARCHAR(50))"))
                conn.execute(text("CREATE TABLE IF NOT EXISTS productos (id INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(100), precio DECIMAL(10,2))"))
            print("[OK] MariaDB lista y tablas creadas.")
            maria_ready = True
        except Exception as e:
            print(f"[ESPERANDO] MariaDB cargando... ({str(e)}).")
            time.sleep(5)

    oracle_ready = False
    while not oracle_ready:
        try:
            conn = get_oracle_conn()
            cursor = conn.cursor()
            try:
                cursor.execute("CREATE TABLE ordenes (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, cliente_id NUMBER, total DECIMAL(10,2), estado VARCHAR2(20))")
                print("[OK] Tabla Oracle creada.")
            except oracledb.DatabaseError as e:
                if 'ORA-00955' in str(e): print("[OK] Tabla Oracle ya existía.")
                else: raise e
            conn.close()
            oracle_ready = True
        except Exception as e:
            print(f"[ESPERANDO] Oracle cargando... Reintentando...")
            time.sleep(5)
    try:
        eng = get_sqlserver_master()
        with eng.connect().execution_options(isolation_level="AUTOCOMMIT") as conn:
            conn.execute(text("IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'AnalyticsDB') CREATE DATABASE AnalyticsDB"))
        
        eng_ana = get_sqlserver_analytics()
        with eng_ana.connect() as conn:
            conn.execute(text("IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='reporte_fin' AND xtype='U') CREATE TABLE reporte_fin (id INT IDENTITY(1,1) PRIMARY KEY, fecha DATETIME DEFAULT GETDATE(), total_dia DECIMAL(15,2), num_ordenes INT)"))
            conn.commit()
        print("[OK] SQL Server lista.")
    except Exception as e: print(f"[ERR] SQL Server: {e}")

def seed_data():
    print(">>> 2. Poblando datos...")
    try:
       
        eng = get_mariadb()
        data_cli = [{"nombre": fake.name(), "ciudad": fake.city()} for _ in range(5)] 
        pd.DataFrame(data_cli).to_sql('clientes', eng, if_exists='append', index=False)
        
       
        conn = get_oracle_conn()
        cursor = conn.cursor()
        for _ in range(5): 
            cursor.execute("INSERT INTO ordenes (cliente_id, total, estado) VALUES (:1, :2, 'PAGADO')", 
                        (random.randint(1,50), round(random.uniform(10,500), 2)))
        conn.commit()
        conn.close()
        print("[OK] Datos insertados.")
    except Exception as e:
        print(f"[WARN] Fallo insertando datos: {e}")

def job_etl():
    print("\n--- JOB ETL: Consolidando Ventas ---")
    try:
        conn = get_oracle_conn()
        df = pd.read_sql("SELECT SUM(total) as TOT, COUNT(*) as CANT FROM ordenes WHERE estado='PAGADO'", conn)
        conn.close()
        
        total = df['TOT'].iloc[0] or 0
        cant = df['CANT'].iloc[0] or 0
        
        eng = get_sqlserver_analytics()
        with eng.connect() as conn:
            conn.execute(text(f"INSERT INTO reporte_fin (total_dia, num_ordenes) VALUES ({total}, {cant})"))
            conn.commit()
            
        print(f"[EXITO] Reporte Financiero Guardado: ${total} en {cant} ordenes.")
    except Exception as e:
        print(f"[FALLO] Error en ETL: {e}")

if __name__ == "__main__":
    print("Iniciando Sistema...")
    setup_db() # Ahora esto asegura que las tablas existan SI o SI antes de seguir
    
    schedule.every(1).minutes.do(seed_data)
    schedule.every(1).minutes.do(job_etl)
    
    seed_data()
    job_etl()
    
    while True:
        schedule.run_pending()
        time.sleep(1)